blank_issues_enabled: false
contact_links:
  - name: Catatan Perkuliahan
    url: https://github.com/abyalax/abyalax/issues/new?template=perkuliahan.md
    about: Gunakan template ini untuk mencatat materi kuliah.
  - name: Catatan Pribadi
    url: https://github.com/abyalax/abyalax/issues/new?template=note_pribadi.md
    about: Gunakan template ini untuk mencatat hal penting secara pribadi.
  - name: User Story
    url: https://github.com/abyalax/abyalax/issues/new?template=user_story_template.md
    about: Gunakan template ini untuk membuat user story.
